# Generated by Django 3.1.2 on 2021-07-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COV19Predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='2021-07-10')),
            ],
        ),
    ]
