# Generated by Django 3.1.2 on 2021-07-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COV19Predictor', '0003_egypt_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='no-country', max_length=50)),
            ],
            options={
                'db_table': 'country_names',
            },
        ),
    ]
